The diploma thesis "Fenrir -- Zum Schutz von OT-Netzwerken" focuses on securing OT networks. To achieve this, a network topology is constructed that aims to realistically simulate a corporate enterprise network, including a virtual IT environment (Active Directory office and server environment) as well as a physical OT environment (programmable logic controllers, associated actuators/sensors, SCADA system, and HMIs).

The IT environment consists of an Active Directory Domain, which includes Windows Servers and Windows Clients, and additional Linux Servers. The Windows servers include two redundant domain controllers and a Microsoft Exchange Server used as a mail server. The Linux servers are used for VPNs and network monitoring.

The OT environment comprises a model of a wastewater treatment plant and its associated monitoring and administrative equipment. This includes, among other things, an Archimedean screw, a rake, water tanks, filters, a dam, pumps and much more. These components are equipped with actuators and sensors and serve as control targets for multiple PLCs. Once the setup is complete, they are also used as attack targets, demonstrating, for example, how an attacker could completely disable the pumps or manipulate them to cause intentional water damage.

To ensure network safety, multiple FortiGate firewalls are used. These firewalls, in conjunction with strict AD-integrated access controls, micro-segmentation of OT operational cells and segmentation of the IT network serve to restrict and monitor data flow.

For continuous surveillance of network traffic a Nozomi Guardian is used. This device is more then just an IDS; by analyzing mirror traffic, it can identify all devices within the network along with their potential vulnerabilties. It then visually presents the gathered information in an intuitive way for network administrators.

The goal is not only to establish a network protected from both external and internal cyberattacks but also to provide detailed documentation of the configuration and security process.