Die Diplomarbeit "Fenrir -- Zum Schutz von OT-Netzwerken" beschäftigt sich mit der Absicherung von OT-Netzwerken. Dazu wird eine Netzwerktopologie aufgebaut, welche ein realitätsgetreues Firmennetzwerk repräsentieren soll, inklusive einem virtuellem IT- (Active Directory Büro- bzw. Serverumgebung) sowie einem physischen OT-Netzwerk (Speicherprogrammierbare Steuerungen, die anzusteuernden Aktoren/Sensoren, SCADA-System, HMIs).

Das IT-Netzwerk besteht aus virtualisierten Windows- bzw. Linux-Computern, die Teil einer Active-Directory-Domain sind. Die Windows-Server sind zwei redundante Domain Controller, als auch ein Microsoft Exchange Server, welcher als Mail-Server eingesetzt wird. Die Linux-Server dagegen dienen für VPNs und Netzwerküberwachung.

Der OT-Bereich besteht aus einem Modell einer Kläranlage und der zugehörigen Gerätschaft zu deren Überwachung und Administration. Diese setzt sich, unter anderem, aus einer archimedischen Schraube, einem Rechen, Wassertanks, Filtern, einem Staudamm und Pumpen zusammen, wobei diese Bauteile mit verbauter Aktorik und Sensorik als Ansteuerungsziele mehrerer SPSen gelten. Diese werden nach Aufbau auch als Angriffsziel verwendet, wobei ein Angriff beispielsweise die Pumpen komplett stilllegen, oder auch durch Manipulation gezielt einen Wasserschaden verursacht werden könnte.

Für die Absicherung des Netzwerks sorgen FortiGate-Firewalls. Diese dienen, unter anderem, gemeinsam mit einer strikten AD-integrierten Zugriffskontrolle und einer Mikrosegmentierung der OT-Betriebszellen als auch des IT-Netzwerks für eine Einschränkung und Überwachung des Datenflusses. 

Zur stetigen Überwachung des Datenverkehrs innerhalb des Netzwerk dient eine Nozomi Guardian. Dieses Gerät ist mehr als nur ein IDS und kann anhand von Mirror-Traffic alle sich im Netzwerk befindenden Geräte gemeinsam mit ihren möglichen Schwachstellen erkennen und leicht ersichtlich für eine/n Netzwerkadministrator/in visualisieren.

Als Ziel gilt nicht nur ein vor externen sowie internen Cyberangriffen abgesichertes Netzwerk aufzustellen, sondern auch eine ausführliche Dokumentation des Konfigurations- beziehungsweise Absicherungsprozesses.